"""SQLite-first persistence foundation: database lifecycle, migrations, transactions,
repositories, serialization and the Clock abstraction. No business workflows."""

from app.persistence.clock import Clock, FrozenClock, SystemClock
from app.persistence.database import MEMORY, Database
from app.persistence.errors import (
    AlreadyExistsError,
    ConcurrencyError,
    CorruptRecordError,
    DuplicateIdempotencyKeyError,
    IntegrityError,
    NotFoundError,
    PersistenceError,
    SchemaVersionError,
)
from app.persistence.records import (
    UNRESOLVED_ATTEMPT_STATES,
    DispatchAttempt,
    DispatchAttemptState,
    IdempotencyRecord,
    KnowledgeFactRecord,
    LedgerEntry,
    MailboxSyncFailure,
    MailboxSyncFailureStatus,
    MailboxSyncState,
    MailboxSyncStatus,
    ConfirmationStatus,
    NotificationStatus,
    OperatorChannelFailure,
    OperatorChannelState,
    OperatorConfirmation,
    OperatorNotification,
    QuotaReservation,
    QuotaReservationState,
)
from app.persistence.unit_of_work import UnitOfWork

__all__ = [
    "MEMORY",
    "UNRESOLVED_ATTEMPT_STATES",
    "AlreadyExistsError",
    "Clock",
    "ConcurrencyError",
    "CorruptRecordError",
    "Database",
    "DispatchAttempt",
    "DispatchAttemptState",
    "DuplicateIdempotencyKeyError",
    "FrozenClock",
    "IdempotencyRecord",
    "IntegrityError",
    "KnowledgeFactRecord",
    "LedgerEntry",
    "MailboxSyncFailure",
    "MailboxSyncFailureStatus",
    "MailboxSyncState",
    "MailboxSyncStatus",
    "ConfirmationStatus",
    "NotificationStatus",
    "OperatorChannelFailure",
    "OperatorChannelState",
    "OperatorConfirmation",
    "OperatorNotification",
    "NotFoundError",
    "PersistenceError",
    "QuotaReservation",
    "QuotaReservationState",
    "SchemaVersionError",
    "SystemClock",
    "UnitOfWork",
]
