"""Typed repository interfaces. Persistence responsibilities only; no business policy.

Conventions:
- ``get`` returns ``None`` when absent; ``add`` raises AlreadyExistsError on a taken
  identity and IntegrityError on a missing foreign key.
- Every mutable aggregate carries its own optimistic-concurrency ``version`` and updates
  with ``update(entity, expected_version)``; the new entity must carry exactly
  ``expected_version + 1``. Semantic fields (status, Campaign.config_version) are never
  used as concurrency tokens.
- A stale ``expected_version`` raises ConcurrencyError; a missing row raises NotFoundError.
- Append-only repositories (audit, provenance, DNC, knowledge metadata, idempotency)
  expose no update or delete methods.
"""

from collections.abc import Collection
from datetime import date, datetime
from typing import Protocol, runtime_checkable

from app.core.enums import CampaignStatus, DNCScope, EscalationStatus, KnowledgeDomain, OutboundStatus
from app.core.models import (
    AuditEvent,
    Campaign,
    CampaignJob,
    CampaignMember,
    Conversation,
    DoNotContactEntry,
    EmailMessage,
    EmailThread,
    EntityRef,
    Escalation,
    FollowUpJob,
    FollowUpPlan,
    KnowledgeChunk,
    KnowledgeSource,
    Lead,
    OperatorCommand,
    OperatorResponse,
    OutboundMessage,
    ProspectCompany,
    ProspectContact,
    ProvenanceRecord,
)
from app.persistence.records import (
    DispatchAttempt,
    IdempotencyRecord,
    KnowledgeFactRecord,
    LedgerEntry,
    QuotaReservation,
)


@runtime_checkable
class ProspectCompanyRepository(Protocol):
    def add(self, company: ProspectCompany) -> None: ...
    def get(self, company_id: str) -> ProspectCompany | None: ...
    def get_by_domain(self, domain: str) -> ProspectCompany | None: ...
    def update(self, company: ProspectCompany, expected_version: int) -> None: ...


@runtime_checkable
class ProspectContactRepository(Protocol):
    def add(self, contact: ProspectContact) -> None: ...
    def get(self, contact_id: str) -> ProspectContact | None: ...
    def get_by_email(self, email: str) -> ProspectContact | None: ...
    def list_by_company(self, company_id: str) -> list[ProspectContact]: ...
    def update(self, contact: ProspectContact, expected_version: int) -> None: ...


@runtime_checkable
class LeadRepository(Protocol):
    def add(self, lead: Lead) -> None: ...
    def get(self, lead_id: str) -> Lead | None: ...
    def update(self, lead: Lead, expected_version: int) -> None: ...
    def list_by_contact(self, contact_id: str) -> list[Lead]: ...
    def list_by_campaign(self, campaign_id: str) -> list[Lead]: ...


@runtime_checkable
class EmailThreadRepository(Protocol):
    def add(self, thread: EmailThread) -> None: ...
    def get(self, thread_id: str) -> EmailThread | None: ...
    def list_by_lead(self, lead_id: str) -> list[EmailThread]: ...
    def update(self, thread: EmailThread, expected_version: int) -> None: ...


@runtime_checkable
class EmailMessageRepository(Protocol):
    def add(self, message: EmailMessage) -> None: ...
    def get(self, message_id: str) -> EmailMessage | None: ...
    def get_by_rfc_message_id(self, rfc_message_id: str) -> EmailMessage | None: ...
    def exists_by_rfc_message_id(self, rfc_message_id: str) -> bool: ...
    def list_by_thread(self, thread_id: str) -> list[EmailMessage]: ...


@runtime_checkable
class CampaignRepository(Protocol):
    def add(self, campaign: Campaign) -> None: ...
    def get(self, campaign_id: str) -> Campaign | None: ...
    def update(self, campaign: Campaign, expected_version: int) -> None: ...
    def list_by_status(self, status: CampaignStatus) -> list[Campaign]: ...


@runtime_checkable
class OutboundMessageRepository(Protocol):
    def add(self, message: OutboundMessage) -> None: ...
    def get(self, outbound_id: str) -> OutboundMessage | None: ...
    def get_by_idempotency_key(self, idempotency_key: str) -> OutboundMessage | None: ...
    def update(self, message: OutboundMessage, expected_version: int) -> None: ...
    def list_by_lead(self, lead_id: str) -> list[OutboundMessage]: ...
    def list_by_status(self, status: OutboundStatus) -> list[OutboundMessage]: ...
    def list_ledger_entries(
        self,
        statuses: Collection[OutboundStatus],
        sending_from: datetime,
        sending_before: datetime,
    ) -> list[LedgerEntry]: ...
    def list_ledger_entries_for_contact(
        self, contact_id: str, statuses: Collection[OutboundStatus]
    ) -> list[LedgerEntry]: ...


@runtime_checkable
class FollowUpPlanRepository(Protocol):
    def add(self, plan: FollowUpPlan) -> None: ...
    def get(self, plan_id: str) -> FollowUpPlan | None: ...
    def update(self, plan: FollowUpPlan, expected_version: int) -> None: ...
    def get_open_for_lead(self, lead_id: str) -> FollowUpPlan | None: ...
    def list_active_due(self, due_at_or_before: datetime, limit: int) -> list[FollowUpPlan]: ...


@runtime_checkable
class DoNotContactRepository(Protocol):
    def add(self, entry: DoNotContactEntry) -> None: ...
    def get(self, entry_id: str) -> DoNotContactEntry | None: ...
    def list_for_value(self, scope: DNCScope, value: str) -> list[DoNotContactEntry]: ...
    def list_active(self, scope: DNCScope, value: str, at: datetime) -> list[DoNotContactEntry]: ...


@runtime_checkable
class EscalationRepository(Protocol):
    def add(self, escalation: Escalation) -> None: ...
    def get(self, escalation_id: str) -> Escalation | None: ...
    def update(self, escalation: Escalation, expected_version: int) -> None: ...
    def list_by_lead(self, lead_id: str) -> list[Escalation]: ...
    def list_by_status(self, status: EscalationStatus) -> list[Escalation]: ...


@runtime_checkable
class OperatorCommandRepository(Protocol):
    def add(self, command: OperatorCommand) -> None: ...
    def get(self, command_id: str) -> OperatorCommand | None: ...
    def get_by_telegram_update_id(self, telegram_update_id: int) -> OperatorCommand | None: ...


@runtime_checkable
class OperatorResponseRepository(Protocol):
    def add(self, response: OperatorResponse) -> None: ...
    def list_for_command(self, command_id: str) -> list[OperatorResponse]: ...


@runtime_checkable
class AuditRepository(Protocol):
    def append(self, event: AuditEvent) -> None: ...
    def get(self, event_id: str) -> AuditEvent | None: ...
    def list_for_subject(self, subject: EntityRef) -> list[AuditEvent]: ...
    def list_by_correlation_id(self, correlation_id: str) -> list[AuditEvent]: ...


@runtime_checkable
class ProvenanceRepository(Protocol):
    def append(self, record: ProvenanceRecord) -> None: ...
    def list_for_artifact(self, artifact: EntityRef) -> list[ProvenanceRecord]: ...


@runtime_checkable
class KnowledgeSourceMetaRepository(Protocol):
    def add(self, source: KnowledgeSource) -> None: ...
    def get(self, source_id: str, version: int) -> KnowledgeSource | None: ...
    def get_latest(self, source_id: str) -> KnowledgeSource | None: ...
    def list_by_domain(self, domain: KnowledgeDomain) -> list[KnowledgeSource]: ...


@runtime_checkable
class IdempotencyRepository(Protocol):
    def reserve(self, key: str, operation: str, created_at: datetime) -> IdempotencyRecord: ...
    def exists(self, key: str) -> bool: ...
    def get(self, key: str) -> IdempotencyRecord | None: ...


@runtime_checkable
class QuotaReservationRepository(Protocol):
    def add(self, reservation: QuotaReservation) -> None: ...
    def get(self, reservation_id: str) -> QuotaReservation | None: ...
    def get_live_for_outbound(self, outbound_id: str) -> QuotaReservation | None: ...
    def list_active_for_date(self, policy_date: date) -> list[QuotaReservation]: ...
    def list_active_for_contact(self, contact_id: str) -> list[QuotaReservation]: ...
    def update(self, reservation: QuotaReservation, expected_version: int) -> None: ...


@runtime_checkable
class DispatchAttemptRepository(Protocol):
    def add(self, attempt: DispatchAttempt) -> None: ...
    def get(self, attempt_id: str) -> DispatchAttempt | None: ...
    def get_by_permit_id(self, permit_id: str) -> DispatchAttempt | None: ...
    def list_for_outbound(self, outbound_id: str) -> list[DispatchAttempt]: ...
    def list_unresolved(self) -> list[DispatchAttempt]: ...
    def update(self, attempt: DispatchAttempt, expected_version: int) -> None: ...


@runtime_checkable
class ConversationRepository(Protocol):
    def add(self, conversation: Conversation) -> None: ...
    def get(self, conversation_id: str) -> Conversation | None: ...
    def get_by_thread(self, thread_id: str) -> Conversation | None: ...
    def list_by_contact(self, contact_id: str) -> list[Conversation]: ...
    def list_by_lead(self, lead_id: str) -> list[Conversation]: ...
    def update(self, conversation: Conversation, expected_version: int) -> None: ...


@runtime_checkable
class FollowUpJobRepository(Protocol):
    def add(self, job: FollowUpJob) -> None: ...
    def get(self, follow_up_id: str) -> FollowUpJob | None: ...
    def get_open_for_conversation(self, conversation_id: str) -> FollowUpJob | None: ...
    def list_for_conversation(self, conversation_id: str) -> list[FollowUpJob]: ...
    def list_claimable(self, now: datetime, limit: int) -> list[FollowUpJob]: ...
    def update(self, job: FollowUpJob, expected_version: int) -> None: ...


@runtime_checkable
class CampaignMemberRepository(Protocol):
    def add(self, member: CampaignMember) -> None: ...
    def get(self, member_id: str) -> CampaignMember | None: ...
    def get_for(self, campaign_id: str, contact_id: str) -> CampaignMember | None: ...
    def get_by_lead(self, lead_id: str) -> CampaignMember | None: ...
    def list_by_campaign(self, campaign_id: str) -> list[CampaignMember]: ...
    def list_by_contact(self, contact_id: str) -> list[CampaignMember]: ...
    def update(self, member: CampaignMember, expected_version: int) -> None: ...


@runtime_checkable
class CampaignJobRepository(Protocol):
    def add(self, job: CampaignJob) -> None: ...
    def get(self, job_id: str) -> CampaignJob | None: ...
    def get_open_for_member(self, member_id: str) -> CampaignJob | None: ...
    def list_for_member(self, member_id: str) -> list[CampaignJob]: ...
    def list_open_for_campaign(self, campaign_id: str) -> list[CampaignJob]: ...
    def list_claimable(self, now: datetime, limit: int) -> list[CampaignJob]: ...
    def update(self, job: CampaignJob, expected_version: int) -> None: ...


@runtime_checkable
class KnowledgeIndexRepository(Protocol):
    def add_chunk(self, chunk: KnowledgeChunk) -> None: ...
    def add_fact(self, fact: KnowledgeFactRecord) -> None: ...
    def list_chunks(self, source_id: str, source_version: int) -> list[KnowledgeChunk]: ...
    def list_chunks_for_sources(
        self, sources: Collection[tuple[str, int]]
    ) -> list[KnowledgeChunk]: ...
    def list_facts_for_sources(
        self, sources: Collection[tuple[str, int]]
    ) -> list[KnowledgeFactRecord]: ...
    def match_chunks(
        self, match_expression: str, sources: Collection[tuple[str, int]]
    ) -> list[KnowledgeChunk]: ...
    def rebuild_search_index(self) -> int: ...
    def count_search_rows(self) -> int: ...
