from enum import StrEnum


class ActorType(StrEnum):
    SYSTEM = "SYSTEM"
    LLM = "LLM"
    OPERATOR = "OPERATOR"
    EXTERNAL = "EXTERNAL"


class RefKind(StrEnum):
    """Kinds of entity a typed reference (EntityRef) may point to."""

    EMAIL_MESSAGE = "EMAIL_MESSAGE"
    EMAIL_THREAD = "EMAIL_THREAD"
    LEAD = "LEAD"
    PROSPECT_COMPANY = "PROSPECT_COMPANY"
    PROSPECT_CONTACT = "PROSPECT_CONTACT"
    CAMPAIGN = "CAMPAIGN"
    OUTBOUND_MESSAGE = "OUTBOUND_MESSAGE"
    FOLLOW_UP_PLAN = "FOLLOW_UP_PLAN"
    MESSAGE_DRAFT = "MESSAGE_DRAFT"
    INTENT_CLASSIFICATION = "INTENT_CLASSIFICATION"
    KNOWLEDGE_QUERY = "KNOWLEDGE_QUERY"
    KNOWLEDGE_EVIDENCE = "KNOWLEDGE_EVIDENCE"
    SEND_PERMIT = "SEND_PERMIT"
    ESCALATION = "ESCALATION"
    OPERATOR_COMMAND = "OPERATOR_COMMAND"
    DNC_ENTRY = "DNC_ENTRY"
