from enum import StrEnum


class EscalationSeverity(StrEnum):
    NORMAL = "NORMAL"
    URGENT = "URGENT"


class EscalationStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    EXPIRED = "EXPIRED"


class EscalationResolution(StrEnum):
    DRAFT_APPROVED = "DRAFT_APPROVED"
    DRAFT_REJECTED = "DRAFT_REJECTED"
    OPERATOR_REPLIED = "OPERATOR_REPLIED"
    TAKEN_OVER = "TAKEN_OVER"
    NO_ACTION = "NO_ACTION"


class EscalationReason(StrEnum):
    KNOWLEDGE_INSUFFICIENT = "KNOWLEDGE_INSUFFICIENT"
    KNOWLEDGE_PARTIAL_REVIEW = "KNOWLEDGE_PARTIAL_REVIEW"
    KNOWLEDGE_CONFLICTING = "KNOWLEDGE_CONFLICTING"
    KNOWLEDGE_STALE = "KNOWLEDGE_STALE"
    KNOWLEDGE_NOT_APPROVED = "KNOWLEDGE_NOT_APPROVED"
    PRICING_OR_COMMERCIAL = "PRICING_OR_COMMERCIAL"
    NEGOTIATION = "NEGOTIATION"
    LEGAL_OR_COMPLAINT = "LEGAL_OR_COMPLAINT"
    COMPETITOR_CLAIM = "COMPETITOR_CLAIM"
    CLAIM_CHECK_FAILED = "CLAIM_CHECK_FAILED"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    SENSITIVE_TONE = "SENSITIVE_TONE"
    INJECTION_SUSPECTED = "INJECTION_SUSPECTED"
    SUPPRESSED_SENDER_INBOUND = "SUPPRESSED_SENDER_INBOUND"
    MEETING_REQUEST = "MEETING_REQUEST"
    LLM_FAILURE = "LLM_FAILURE"
    OPERATOR_REQUESTED = "OPERATOR_REQUESTED"
    # Inbound-flow reasons (Stage 6).
    CLASSIFIER_FAILURE = "CLASSIFIER_FAILURE"
    SUFFICIENCY_FAILURE = "SUFFICIENCY_FAILURE"
    COMPOSER_FAILURE = "COMPOSER_FAILURE"
    CONTRACT_VIOLATION = "CONTRACT_VIOLATION"
    UNCLEAR_INTENT = "UNCLEAR_INTENT"
    NON_SALES = "NON_SALES"
    REFERRAL = "REFERRAL"
    NO_ANSWERABLE_QUESTIONS = "NO_ANSWERABLE_QUESTIONS"
    INVALID_LEAD_TRANSITION = "INVALID_LEAD_TRANSITION"
    AMBIGUOUS_THREAD = "AMBIGUOUS_THREAD"
    AMBIGUOUS_LEAD = "AMBIGUOUS_LEAD"
    UNSUPPORTED_CONTENT = "UNSUPPORTED_CONTENT"
    UNASSESSED_QUESTIONS = "UNASSESSED_QUESTIONS"
    UNVERIFIED_THREAD_REFERENCE = "UNVERIFIED_THREAD_REFERENCE"
    STALE_ANALYSIS = "STALE_ANALYSIS"
    INTERNAL_ERROR = "INTERNAL_ERROR"
