from enum import StrEnum


class EscalationSeverity(StrEnum):
    NORMAL = "NORMAL"
    URGENT = "URGENT"


class EscalationStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    EXPIRED = "EXPIRED"


class EscalationResolution(StrEnum):
    DRAFT_APPROVED = "DRAFT_APPROVED"
    DRAFT_REJECTED = "DRAFT_REJECTED"
    OPERATOR_REPLIED = "OPERATOR_REPLIED"
    TAKEN_OVER = "TAKEN_OVER"
    NO_ACTION = "NO_ACTION"


class EscalationReason(StrEnum):
    KNOWLEDGE_INSUFFICIENT = "KNOWLEDGE_INSUFFICIENT"
    KNOWLEDGE_PARTIAL_REVIEW = "KNOWLEDGE_PARTIAL_REVIEW"
    KNOWLEDGE_CONFLICTING = "KNOWLEDGE_CONFLICTING"
    KNOWLEDGE_STALE = "KNOWLEDGE_STALE"
    KNOWLEDGE_NOT_APPROVED = "KNOWLEDGE_NOT_APPROVED"
    PRICING_OR_COMMERCIAL = "PRICING_OR_COMMERCIAL"
    NEGOTIATION = "NEGOTIATION"
    LEGAL_OR_COMPLAINT = "LEGAL_OR_COMPLAINT"
    COMPETITOR_CLAIM = "COMPETITOR_CLAIM"
    CLAIM_CHECK_FAILED = "CLAIM_CHECK_FAILED"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    SENSITIVE_TONE = "SENSITIVE_TONE"
    INJECTION_SUSPECTED = "INJECTION_SUSPECTED"
    SUPPRESSED_SENDER_INBOUND = "SUPPRESSED_SENDER_INBOUND"
    MEETING_REQUEST = "MEETING_REQUEST"
    LLM_FAILURE = "LLM_FAILURE"
    OPERATOR_REQUESTED = "OPERATOR_REQUESTED"
