"""Provider-neutral email transport contracts.

A transport receives a fully built, immutable request and reports what the provider
said. It cannot change recipients or content, approve anything, or reach the database:
it gets only the request object. A future real adapter implements ``EmailTransport``.

Outcome meanings:
- ACCEPTED: the provider confirmed it accepted the message for delivery. This is not
  proof of delivery to the recipient.
- NOT_ACCEPTED: the provider definitively did not accept it (a rejection), or the
  transport knows the request never left (``NotSubmittedError``).
- UNKNOWN: the transport cannot say (timeout, lost connection, lost response). The
  message may or may not have been accepted; it must be reconciled, never resent.

Any exception other than ``NotSubmittedError`` is treated as UNKNOWN.
"""

from enum import StrEnum
from typing import Protocol, Self

from pydantic import model_validator

from app.core.models.base import CoreModel
from app.core.models.types import EmailAddress, EntityId, NonEmptyStr


class TransportOutcome(StrEnum):
    ACCEPTED = "ACCEPTED"
    NOT_ACCEPTED = "NOT_ACCEPTED"
    UNKNOWN = "UNKNOWN"


class TransportRequest(CoreModel):
    """Built only from persisted, application-owned data. ``request_id`` is the attempt
    identity; ``rfc_message_id`` is generated by the application, stable per attempt."""

    request_id: EntityId
    rfc_message_id: NonEmptyStr
    sender_mailbox: EmailAddress
    sender_name: NonEmptyStr
    recipient: EmailAddress
    subject: NonEmptyStr
    body: NonEmptyStr
    in_reply_to: NonEmptyStr | None = None
    references: tuple[NonEmptyStr, ...] = ()


class TransportResult(CoreModel):
    outcome: TransportOutcome
    # Stable code, never a raw provider or exception message.
    reason_code: NonEmptyStr
    provider_message_id: NonEmptyStr | None = None
    # Only for NOT_ACCEPTED: whether another attempt could succeed (e.g. a transient
    # rejection or a failure before submission), as opposed to a permanent rejection.
    retryable: bool = False

    @model_validator(mode="after")
    def _check(self) -> Self:
        if (self.outcome is TransportOutcome.ACCEPTED) != (self.provider_message_id is not None):
            raise ValueError("provider_message_id is required for, and only allowed on, ACCEPTED")
        if self.retryable and self.outcome is not TransportOutcome.NOT_ACCEPTED:
            raise ValueError("only NOT_ACCEPTED can be retryable")
        return self


class NotSubmittedError(Exception):
    """Raised by a transport only when it knows nothing left the process (e.g. the
    connection could not be opened). Anything else is an UNKNOWN outcome."""

    def __init__(self, reason_code: str) -> None:
        self.reason_code = reason_code
        super().__init__(reason_code)


class EmailTransport(Protocol):
    def submit(self, request: TransportRequest) -> TransportResult: ...


class ReconciliationFinding(StrEnum):
    """What a read-only lookup positively established about one earlier request.

    Only ACCEPTED and REJECTED_FINAL resolve an attempt. REJECTED_FINAL requires positive
    evidence: the provider holds a record of this exact request (by request id or
    Message-ID) in a terminal, non-accepted state. The absence of a record is never
    proof of non-acceptance: the original submission may still be in flight, or the
    provider may not have indexed it yet; that is NOT_FOUND and keeps the attempt
    unresolved, however complete ("authoritative") the source claims to be.
    """

    ACCEPTED = "ACCEPTED"
    REJECTED_FINAL = "REJECTED_FINAL"
    NOT_FOUND = "NOT_FOUND"
    UNKNOWN = "UNKNOWN"


class ReconciliationResult(CoreModel):
    finding: ReconciliationFinding
    reason_code: NonEmptyStr
    provider_message_id: NonEmptyStr | None = None
    # Only for REJECTED_FINAL: whether a new attempt could succeed.
    retryable: bool = False

    @model_validator(mode="after")
    def _check(self) -> Self:
        if (self.finding is ReconciliationFinding.ACCEPTED) != (self.provider_message_id is not None):
            raise ValueError("provider_message_id is required for, and only allowed on, ACCEPTED")
        if self.retryable and self.finding is not ReconciliationFinding.REJECTED_FINAL:
            raise ValueError("only REJECTED_FINAL can be retryable")
        return self

    def as_transport_result(self) -> TransportResult:
        if self.finding is ReconciliationFinding.ACCEPTED:
            return TransportResult(
                outcome=TransportOutcome.ACCEPTED, reason_code=self.reason_code, provider_message_id=self.provider_message_id
            )
        if self.finding is ReconciliationFinding.REJECTED_FINAL:
            return TransportResult(outcome=TransportOutcome.NOT_ACCEPTED, reason_code=self.reason_code, retryable=self.retryable)
        return TransportResult(outcome=TransportOutcome.UNKNOWN, reason_code=self.reason_code)


class DispatchReconciler(Protocol):
    """Read-only lookup of what happened to an earlier request. Never submits.

    Not every provider supports this; without a reconciler, or without positive
    evidence, unresolved attempts stay unresolved for an operator."""

    def lookup(self, request_id: str, rfc_message_id: str) -> ReconciliationResult: ...
